repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.6.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-added-large-files
    args: [--maxkb=2048]
  - id: check-merge-conflict
- repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
  rev: v0.4.5
  hooks:
  - id: ruff
    types_or: [python, pyi, jupyter]
    args: [--fix, --exit-non-zero-on-fix]
- repo: https://github.com/kynan/nbstripout
  rev: 0.7.1
  hooks:
    - id: nbstripout
      types_or: [jupyter]
      exclude: ^reports/notebooks
